### ISSUE TITLE
 Java服务注册成功，但在zookeeper里没有显示该节点 Java service registration was successful, but the node was not displayed in zookeeper

### ISSUE THREAD

**Issue by xiangnuans** [gxcsoccer/sofa-rpc-java-demo#1]
Java producer service runs successfully, node service invocation is implemented through zookeeper, the invocation is successful, but the registered node of Java service can not be obtained on zookeeper service. Why?
![17_58_42__01_23_2019](https://user-images.githubusercontent.com/24558814/51598893-70f1c300-1f39-11e9-845c-93652450cf0b.jpg)
![17_59_40__01_23_2019](https://user-images.githubusercontent.com/24558814/51598899-751de080-1f39-11e9-83bb-498dd3646ef1.jpg)

**Comment by xiangnuans** [comment]
@gxcsoccer

**Comment by gxcsoccer** [comment]
你用的是 sofa-rpc 吧

**Comment by xiangnuans** [comment]
@gxcsoccer 
1. node服务和Java服务注册到zookeeper名称为什么是相同的？不应该是以服务名称注册的吗？这个地方不明白~
2. node作为提供者，Java作为消费者的时候，Node服务一开始的入口是`ProtoService.proto`，然后调rpc目录下的ProtoService的echoObj方法吗？这个能详细介绍下吗
![17_31_28__01_24_2019](https://user-images.githubusercontent.com/24558814/51668944-503f7100-1ffe-11e9-9758-abf699796fb9.jpg)
从图上是可以看出提供者和消费者都是在sofa-rpc下，但我在两个服务都没有找到sofa-rpc的名称，不明白

**Comment by gxcsoccer** [comment]
@CoCoyh 没看懂你的问题

1. node 和 java 暴露服务没什么区别，只要暴露的服务一样，注册到 zk 的名字就一样
2. ProtoService.proto 只是一个接口定义，有了接口定义，提供者知道该提供什么接口，消费者知道该怎么调用。根据消费者调用的请求（包含服务名、方法名、参数等）来路由到具体的方法

**Comment by xiangnuans** [comment]
@gxcsoccer 第二个问题懂了，可第一个问题还是不太懂，node和Java服务中都没有看到sofa-rpc，zookeeper这里为什么是sofa-rpc?
![09_53_51__01_25_2019](https://user-images.githubusercontent.com/24558814/51720156-6cd3bb80-2087-11e9-9832-4b22ea6c07d3.jpg)

**Comment by gxcsoccer** [comment]
> @gxcsoccer 第二个问题懂了，可第一个问题还是不太懂，node和Java服务中都没有看到sofa-rpc，zookeeper这里为什么是sofa-rpc?

这个是约定，你用 sofa-rpc，那就是 sofa-rpc，如果你用 dubbo，那就是 dubbo

**Comment by xiangnuans** [comment]
@gxcsoccer 懂了，谢谢～
sofa-rpc框架与淘宝的HSF、dubbo有什么关系和区别？因为网上差了很多资料，好像都没怎么说明白，关于HSF，网上资料感觉也是很少，sofa-rpc感觉文档资料比较完善，很赞～

希望大老能再出一个以HSF框架的java-rpc-demo，与node互相调用～

**Comment by gxcsoccer** [comment]
@CoCoyh 外部不用关注 HSF 了，就是 dubbo
